### ISSUE TITLE
面试题：使用 CSS 画一个三角形

### ISSUE THREAD

**Issue by sisterAn** [sisterAn/JavaScript-Algorithms#123]

**Comment by Agan29** [comment]
# 通过border模拟实现

当div 的宽高为0，存在边框的时候，四条边框的中心将会是一个点，通过设置其他三条边框的透明度，实现三角形。

```css
div{
  width:0;
  height:0;
  border-width:8px;
  border-top-color: transparent;
  border-right-color: transparent;
  border-bottom-color: transparent;
  border-left-color: red;
}

```
