### ISSUE TITLE
实现一个信号灯控制器

### ISSUE THREAD

**Issue by sisterAn** [sisterAn/JavaScript-Algorithms#155]
/** 1. 信号灯控制器
用 React 实现一个信号灯（交通灯）控制器，要求：
1. 默认情况下，
  1.1. 红灯亮20秒，并且最后5秒闪烁
  1.2. 绿灯亮20秒，并且最后5秒闪烁
  1.3. 黄灯亮10秒
  1.4. 次序为 红-绿-黄-红-绿-黄
2. 灯的个数、颜色、持续时间、闪烁时间、灯光次序都可配置，如：
   lights=[{color: '#fff', duration: 10000, twinkleDuration: 5000}, ... ]
*/

import React from 'react'
import ReactDOM from 'react-dom'
class TrafficLightItem extends React.Component {
}

**Comment by zhang0ZGC** [comment]
我的想法是灯的闪烁就用了CSS的动画加上设定的延迟时间🤣利用 CSS 变量设置灯的颜色及闪烁的时间点。
```css
@keyframes twinkle {
  0% {
    /*background-color: #10a54a;*/
    background-color: var(--color);
  }
  50% {
    background-color: #000;
  }
  100% {
    /*background-color: #10a54a;*/
    background-color: var(--color);
  }
}

.light {
  background-color: #000;
  width: 60px;
  height: 60px;
  border-radius: 30px;
  margin: 4px;
}

.light.active {
  background-color: var(--color);
  animation: twinkle 1s ease-in-out infinite var(--twinkle-delay);
}
``` 

然后给灯设置上CSS变量：
```tsx
type LightConf = {
  color: string;
  duration: number;
  twinkleDuration?: number;
};

type TrafficLightItemProps = {
  active?: boolean;
} & LightConf;

class TrafficLightItem extends React.Component<TrafficLightItemProps> {
  render() {
    const { active, color, duration, twinkleDuration } = this.props;
    let styles: any = {
      "--color": color,
      "--twinkle-delay": duration - (twinkleDuration || 0) + "ms"
    };
    return <div className={`light ${active ? "active" : ""}`} style={styles} />;
  }
}
```

然后整个信号灯的框架组件，设置灯的配置，内部状态记录当前亮的灯的序号，并在组件挂在后，利用 setTimeout 循环修改当前灯的序号

```tsx
type TrafficLightState = { currentIdx: number; lights: LightConf[] };
class TrafficLight extends React.Component<{}, TrafficLightState> {
  constructor(props: any) {
    super(props);

    this.timer = null;

    this.state = {
      lights: [
        { color: "red", duration: 20000, twinkleDuration: 5000 },
        { color: "green", duration: 20000, twinkleDuration: 5000 },
        { color: "yellow", duration: 10000 }
      ],
      currentIdx: 0
    };
  }

  componentDidMount() {
    this.startTimer();
  }

  componentWillUnmount() {
    clearTimeout(this.timer);
  }

  startTimer = () => {
    const { lights, currentIdx } = this.state;

    const nextIdx: number = lights.length - 1 > currentIdx ? currentIdx + 1 : 0;
    this.timer = setTimeout(() => {
      this.setState({ currentIdx: nextIdx });

      this.startTimer();
    }, lights[currentIdx].duration);
  };

  render() {
    const { currentIdx, lights } = this.state;

    return (
      <div>
        {lights.map((light, k) => (
          <TrafficLightItem key={k} {...light} active={currentIdx === k} />
        ))}
      </div>
    );
  }
}
```

也不知道有没有跑题，感觉会有点问题。。如果js很卡了的话，最后黄灯可能会闪。。

挫代码😂 https://codesandbox.io/s/new-rain-9pdzn
